# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - dikshita  # Ensure that the branch name is correct and matches your repository

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: echo "Hello World"
    displayName: 'Run a simple script'


