# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - features/dikshita

pool:
  vmImage: 'ubuntu-latest'

steps:
# Step 1: Check out the code from GitHub
- task: Checkout@1

# Step 2: Set up Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'

# Step 3: Echo test step
- script: |
    echo "Pipeline is working"
  displayName: 'Test pipeline'


