# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# azure-pipelines.yml
trigger:
  branches:
    include:
      - features/dikshita  # Change this to your branch if necessary

pool:
  vmImage: 'ubuntu-latest'

steps:
# Step 1: Check out the code from GitHub
- task: Checkout@1

# Step 2: Set up Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'  # Use the Node.js version you need

# Step 3: Install dependencies and build the React app
- script: |
    npm install
    npm run build
  displayName: 'Install and Build'
  env:
    NEXT_PUBLIC_SUPABASE_URL: $(NEXT_PUBLIC_SUPABASE_URL)
    NEXT_PUBLIC_SUPABASE_ANON_KEY: $(NEXT_PUBLIC_SUPABASE_ANON_KEY)
    SUPABASE_SERVICE_ROLE_KEY: $(SUPABASE_SERVICE_ROLE_KEY)
    REPLICATE_API_TOKEN: $(REPLICATE_API_TOKEN)

# Step 4: Log in to Docker Hub
- task: Docker@2
  inputs:
    containerRegistry: 'DockerHubServiceConnection'
    command: 'login'

# Step 5: Build Docker image
- task: Docker@2
  inputs:
    containerRegistry: 'DockerHubServiceConnection'
    repository: 'your-dockerhub-username/emoji-maker'
    command: 'buildAndPush'
    Dockerfile: 'emojigenerator/Dockerfile'
    tags: |
      latest
      $(Build.BuildId)

