# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - dikshita  # Or your working branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  NEXT_PUBLIC_SUPABASE_URL: $(NEXT_PUBLIC_SUPABASE_URL)
  SUPABASE_SERVICE_ROLE_KEY: $(SUPABASE_SERVICE_ROLE_KEY)
  REPLICATE_API_TOKEN: $(REPLICATE_API_TOKEN)

steps:
 # Step 2: Set up Node.js version
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
      checkLatest: true

  # Step 3: Install Dependencies
  - script: |
      npm install
    displayName: 'Install Dependencies'

  # Step 4: Build Next.js App with Environment Variables
  - script: |
      NEXT_PUBLIC_SUPABASE_URL=$(NEXT_PUBLIC_SUPABASE_URL) \
      SUPABASE_SERVICE_ROLE_KEY=$(SUPABASE_SERVICE_ROLE_KEY) \
      REPLICATE_API_TOKEN=$(REPLICATE_API_TOKEN) \
      npm run build
    displayName: 'Build Application'
  
  
