# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - dikshita  # Change to your branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Step 1: Set up Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'  # Specify the Node.js version you need

  # Step 2: Install dependencies and build the React app
  - script: |
      npm install
      npm run build
    displayName: 'Install and Build React App'

  
  

